### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by hannayurchyk** [DanHrmti/ECRL#1]
Hi,

While trying to run your code, I ran into several dependency issues. 

In the prerequisites section, you mention having torch 2.0.1 and stable-baseline3 1.5.0. However, your requirements.txt has torch 2.1.2. Furthermore, I can't install gym 0.21.0 without downgrading to python 3.7. I have more similar issues that require newer versions of stable-baseline3. 

Also, I have permission denied when trying to run python main.py -c config/push_t (for wandb).  

Would you mind helping me to get started running your code in conda? 

Thanks!

**Comment by DanHrmti** [comment]
Hi,

Thank you for pointing out the discrepancy between the torch versions in the requirements.txt and the README, the code should work with both versions of torch though.

Regarding the stable-baselines3 version, I developed the RL code on top of version 1.5.0 and therefore it is a hard constraint.
I have also had some problems with the installation of gym 0.21.0 and this provided the solution: https://github.com/openai/gym/issues/3176
In short, just downgrade setuptools to an earlier version that doesn't break the gym 0.21.0 installation.
`pip install setuptools==66` worked for me.

To solve the permission denied for wandb you can do one of the following:
1. Disable wandb logging by setting `WANDB: log: False` in the `config/push_t/Config.yaml`
2. Fill in your wandb username in the `wandb.init(entity="")` line in the main.py script

I am happy to help, let me know if you have any other issues and I will do my best to answer questions or push any required fixes to the repository.

Dan

**Comment by hannayurchyk** [comment]
Thank you for the fast reply, everything is running smoothly now! I will let you know if any other issue arises. 

Best, 
Hanna
